class Catalogmodel{
  static final items = [
    Item(id: 1,
        name: "Leanne Graham",
        username: "Bret",
        email: "Sincere@april.biz",
        phone: "1-770-736-8031 x56442",
        website: "hildegard.org",
        image: 'assets/Rectangle 21.png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 2,
      name: "Ervin Howell",
      username: "Antonette",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (1).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 3,
      name: "Clementine Bauch",
      username: "Samantha",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (2).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 4,
      name: "Patricia Lebsack",
      username: "Karianne",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (3).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 5,
      name: "Chelsey Dietrich",
      username: "Kamren",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (4).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 6,
      name: "Leanne Graham",
      username: "Leopoldo_Corkery",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (5).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 7,
      name: "Kurtis Weissnat",
      username: "Elwyn.Skiles",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (6).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 8,
      name: "Ervin Howell",
      username: "Maxime_Nienow",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (7).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 9,
      name: "Glenna Reichert",
      username: "Delphine",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (1).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),
    Item(id: 10,
      name: "Clement DuBuque",
      username: "Moriah.Stanton",
      email: "Sincere@april.biz",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      image: 'assets/Rectangle 21 (4).png',
      address: 'Victor Plains,Suite 879,Wisokyburgh,90566-7771',
    ),

  ];
}

class Item {
  final int id;
  final String name;
  final String username;
  final String email;
  final String image;
  final String phone;
  final String website;
  final String address;


  Item({ required this.id,
    required this.name,
    required this.username ,
    required this.email,
    required this.image,
    required this.phone,
    required this.website,
    required this.address,
  });

}